mylist = list(("this","is","my","era"))
print(mylist)
mylist.append("Times")
print(mylist)
mylist.insert(-1,"Time")
print(mylist)
mylist.insert(2,"Time")
print(mylist)
mylist.extend(["EXP","W#"])
print(mylist)
mylist.extend(("EXP","W#"))
print(mylist)